# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: edools-api 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "edools-api"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Vinicius Kastrup"]
  s.date = "2014-07-29"
  s.description = "\n    With this gem you'll be able to access and manipulate all the data of your School or Organization\n    hosted at Edools.\n  "
  s.email = "viniciusmkm@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/edools.rb",
    "lib/edools/config.rb",
    "lib/edools/core.rb",
    "lib/edools/core/base.rb",
    "lib/edools/core/enrollment.rb",
    "lib/edools/core/organization.rb",
    "lib/edools/core/paginated_collection.rb",
    "lib/edools/core/registration.rb",
    "lib/edools/core/school.rb",
    "lib/edools/core/school_product.rb",
    "lib/edools/core/student.rb",
    "lib/edools/initialization.rb",
    "spec/edools/core/base_spec.rb",
    "spec/edools/core/enrollment_spec.rb",
    "spec/edools/core/organization_spec.rb",
    "spec/edools/core/registration_spec.rb",
    "spec/edools/core/school_product_spec.rb",
    "spec/edools/core/school_spec.rb",
    "spec/edools/core/student_spec.rb",
    "spec/fixtures/vcr_cassettes/Edools_Core_Student/create_the_student.yml",
    "spec/fixtures/vcr_cassettes/Edools_Core_Student/destroy_the_student.yml",
    "spec/fixtures/vcr_cassettes/Edools_Core_Student/finds_all_student.yml",
    "spec/fixtures/vcr_cassettes/Edools_Core_Student/finds_the_student.yml",
    "spec/fixtures/vcr_cassettes/Edools_Core_Student/update_the_student.yml",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/Edools/edools-api"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "This gem is a Ruby wrapper for all Edools API's"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activeresource>, [">= 4.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.0.0"])
      s.add_development_dependency(%q<vcr>, ["~> 2.9.2"])
      s.add_development_dependency(%q<webmock>, ["~> 1.18.0"])
      s.add_development_dependency(%q<pry>, ["~> 0.10.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<activeresource>, [">= 4.0.0"])
      s.add_dependency(%q<rspec>, ["~> 3.0.0"])
      s.add_dependency(%q<vcr>, ["~> 2.9.2"])
      s.add_dependency(%q<webmock>, ["~> 1.18.0"])
      s.add_dependency(%q<pry>, ["~> 0.10.0"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<activeresource>, [">= 4.0.0"])
    s.add_dependency(%q<rspec>, ["~> 3.0.0"])
    s.add_dependency(%q<vcr>, ["~> 2.9.2"])
    s.add_dependency(%q<webmock>, ["~> 1.18.0"])
    s.add_dependency(%q<pry>, ["~> 0.10.0"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

